## Arrays Slicing Challenge

In [1]:
import numpy as np

Why doesn't the following create a two-dimensional array?

In [ ]:
array = np.array((1, 0, 0), 
                 (0, 1, 0), 
                 (0, 0, 1, dtype=float)

Answer:
The above does not create a two-dimensional array because there is a syntax-error. Instead, the numpy array should have a single tuple that contains all of the tuples that represent a row in the two-dimensional array.

The corrected way is as follows:

In [3]:
array = np.array(((1, 0, 0), 
                  (0, 1, 0), 
                  (0, 0, 1)), dtype=float)

array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

What is the difference between the following?

In [4]:
a = np.array([0, 0, 0])
a

array([0, 0, 0])

In [5]:
a = np.array([[0, 0, 0]])
a

array([[0, 0, 0]])

The first code creates a one-dimensional NumPy array with three elements of 3 0's (hence a length of 3). The shape is thus (3,).

However, the second code creates a two-dimensional array with one row and three columns. It has one row and three elements of 3 0's. 
Thus, the shape of the array is (1, 3).

In [7]:
arr = np.linspace(1, 48, 48).reshape(3, 4, 4)

arr

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

Slice or index the array to find 20:

In [8]:
# 1 represents the middle set (index one) within the first dimension.
# 0 represents the first list within the second dimension.
# 3 represents the fourth value of the list in the third dimension.
arr[1, 0, 3]

20.0

Slice or index the array to find [9., 10., 11., 12.]

In [9]:
arr[0, 2]
# An alternative way of writing this is: arr[0][2]

array([ 9., 10., 11., 12.])

Slice or index the array to find [[33., 34., 35., 36], [37., 38., 39., 40.], [41., 42., 43., 44.], [45., 46., 47., 48.]]

In [10]:
arr[2]

array([[33., 34., 35., 36.],
       [37., 38., 39., 40.],
       [41., 42., 43., 44.],
       [45., 46., 47., 48.]])

Slice or index the array to find [[5., 6.], [21., 22.], [37., 38.]]

In [18]:
# The : (colon) selects all of the arrays within the first dimension.
# The 1 shows that we want to look at the second array (second line/row) in the second dimension.
# The :2 shows that we want the values at index 0 and 1 (thus, up to 2) from the third dimension (looking at the columns).
arr[:, 1, :2]

array([[ 5.,  6.],
       [21., 22.],
       [37., 38.]])

Slice or index the array to find [[36., 35.], [40., 39.], [44., 43.], [48., 47.]]

In [45]:
# The first '2' selects the second index of the first dimension.
# The : (colon) selects all of the values in the second dimension.
# The 2: is used to select all of the values indexed from 2 to the end.
# The [:, ::-1] reverses the order of the values from each the list (in the second dimension) of what has already been selected.
arr[2, :, 2:][:, ::-1]

array([[36., 35.],
       [40., 39.],
       [44., 43.],
       [48., 47.]])

Slice or index the array to find [[13., 9., 5., 1.], [29., 25., 21., 17.], [45., 41., 37., 33.]]

In [47]:
# The first colon is used to select all of the elements (lists) of the first dimension.
# The second colon selects all of the rows of the lists in the second dimension.
# The 0 selects all of the values at index 0 (the first column) in the third dimension.
# The above is applied here to reverse the order of the elements in each of the lists in the second dimension.
arr[:, :, 0][:, ::-1]

array([[13.,  9.,  5.,  1.],
       [29., 25., 21., 17.],
       [45., 41., 37., 33.]])

Slice or index the array to find [[1., 4.], [45., 48.]]

In [98]:
# The ::2 selects the first row and the last row (steps of 2) in the array along the first layer.
# The ::3 selects the first and fourth row of the sets selected.
# The ::3 slices to select the first and fourth columns.
# Then, we reshape it into a two-dimensional array and store it in a variable called 'modified_array'.
# Then, we select the first and last row (::3) and all of the columns of the modified array.
subarray = arr[::2, ::3, ::3]
modified_array = subarray.reshape(-1,2) # 2-d array
modified_array[::3, :]

array([[ 1.,  4.],
       [45., 48.]])

Slice or index the array to find [[25., 26., 27., 28.], [29., 30., 31., 32.], [33., 34., 35., 36.], [37., 38., 39., 40.]]

In [124]:
# This selects the last two sets.
subarray2 = arr[1:, :, :]
subarray2

array([[[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

In [125]:
# This selects the last two rows and all of the values in the columns of 'subarray2' from the first set.
sub1 = subarray2[0, 2:, :]
print(sub1)
# This selects the first two rows and all of the values in the columns of 'subarray2' from the second set.
sub2 = subarray2[1, :2, :]
print(sub2)

[[25. 26. 27. 28.]
 [29. 30. 31. 32.]]
[[33. 34. 35. 36.]
 [37. 38. 39. 40.]]


In [121]:
# To concatenate sub1 and sub2 into a two-dimensional array.
selected_rows = np.concatenate((sub1, sub2), axis=0)
selected_rows


array([[25., 26., 27., 28.],
       [29., 30., 31., 32.],
       [33., 34., 35., 36.],
       [37., 38., 39., 40.]])